### PR TITLE
Do not merge -- Just trying make Circle CI happy

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cclauss** [comment]
@dsjoerg Can you please go to https://circleci.com/gh/ggtracker/sc2reader/59 and at the top of the page, under "Parallelism" set us to two containers instead of just one?  We want Python 2 testing and Python 3 testing to run in parallel in two separate containers.

**Comment by dsjoerg** [comment]
OK @cclauss I set parallelism to 2, but FYI it put up a message saying "These settings are only for 1.0 builds. To define parallelism for 2.0 jobs, read our documentation." with a link to https://circleci.com/docs/2.0/configuration-reference/#jobs

**Comment by cclauss** [comment]
My suggestion is that we turn Travis back on and we run both Circle and Travis in parallel.  Github does a very nice job of running multiple CIs in parallel.  Circle will run the non-flake8 tests and Travis will run the flake8 tests.  I just can not seem to tame Circle CI.

**Comment by dsjoerg** [comment]
@cclauss works for me

**Comment by cclauss** [comment]
Fixed in #47

**Comment by cclauss** [comment]
Fixed in #47

**Pull request closed without merging**
