### PR TITLE
Add Python 2.7 and 3.6 to the testing and flake8 as well

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cclauss** [comment]
What is with the Circle CI processes?  Do they ever execute?  Do they give you output?  Or is there a misconfiguration in the circle.yml file?

**Comment by cclauss** [comment]
Status looks good https://status.circleci.com/ but none of these CI builds ever run.

**Comment by GraylinKim** [comment]
I'm curious why you switched to CircleCI @dsjoerg.

@cclauss you might try a PR that fixes the circle.yml file which it seems has changed significantly with version 2. http://circleci.com/docs/2.0/configuration-reference/

**Comment by ghost** [comment]
@GraylinKim CircleCI can be actually better than travis - it has better free plan (4 concurrent builds for open-source projects).
And also there's a free plan for closed-source(!) projects

**Comment by dsjoerg** [comment]
@GraylinKim I forget why I switched to CircleCI, I vaguely remember there was something I needed Travis to do but I couldnt get it to do what I wanted and it was easier to switch.

**Comment by dsjoerg** [comment]
@cclauss I had CircleCI set up to run tests on every commit to the `upstream` branch (which is our primary branch).  However I did not have it set to run on PRs.  I switched that setting just now, so from now on it will run tests on PRs as well.

**Pull request merged**
