### PR TITLE
Dialog control event

### PR DESCRIPTION
**Pull request by Andrene**
Adds the DialogControlEvent game event type.

This is for interactions with dialogs ingame and allows for some neat data collection as it looks to generate an event when a trigger modifys a dialog field aswell.

Control ID seems for the most part useless
Event types seem to match with the ones listed here https://mapster.talv.space/galaxy/reference/preset-control-event-type
Event data contains what a dialog text box was changedto, if a check box checked or unchecked, etc

### CODE REVIEW

**Comment by Andrene** [comment]
Style check is failing on a function since it thinks "assertIn" is a typo :)
`self.assertIn("PlayerLeaveEvent", capturedOutput.getvalue())`

**Comment by cclauss** [comment]
Add `assertin` (all lowercase) to this line.
https://github.com/ggtracker/sc2reader/blob/a7778d0436ba37540bfd11f1892a502f5b9c1456/.circleci/config.yml#L21

**Review by StoicLoofah — APPROVED** [review]
Do you mind running black so it can clean up the formatting?

I can also pop it on top if it's tricky for you to get that in

**Comment by Andrene** [comment]
Yep, it was a wee agressive in readers.py

**Comment by StoicLoofah** [comment]
Thanks!

**Pull request merged**
