### PR TITLE
Workaround for missing speed in GAME_SPEED_FACTOR

### LINKED ISSUE #101: Unable to parse alphastar replays
Bumped into this error

```
  File "/home/kevin/sc2reader/sc2reader/factories/sc2factory.py", line 85, in load_replay
    return self.load(Replay, source, options, **new_options)
  File "/home/kevin/sc2reader/sc2reader/factories/sc2factory.py", line 143, in load
    return self._load(cls, resource, filename=filename, options=options)
  File "/home/kevin/sc2reader/sc2reader/factories/sc2factory.py", line 152, in _load
    obj = cls(resource, filename=filename, factory=self, **options)
  File "/home/kevin/sc2reader/sc2reader/resources.py", line 302, in __init__
    self.load_all_details()
  File "/home/kevin/sc2reader/sc2reader/resources.py", line 446, in load_all_details
    self.load_details()
  File "/home/kevin/sc2reader/sc2reader/resources.py", line 435, in load_details
    self.length.seconds / GAME_SPEED_FACTOR[self.expansion][self.speed]
KeyError: ''
```

on [this replay](https://lotv.spawningtool.com/53947/). I got the same error on other replays, though I'm not sure it applies to all of them. The entire replay pack is at https://deepmind.com/research/open-source/alphastar-resources

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #101

### CODE REVIEW

**Review by StoicLoofah — COMMENTED** [review]
Thanks for looking at this! I have to admit that I'm not really familiar with `real_length`, but looking at the speed factors, which can be fractional, it seems like floats can certainly exist here

https://github.com/ggtracker/sc2reader/blob/c01974330b664cee59c9bf4ae7f4c7b45aaa9e6c/sc2reader/constants.py#L51

**Comment by cclauss** [comment]
So you want me to default to __0.6__ instead of 1?

**Comment by StoicLoofah** [comment]
Sorry for being unclear: I missed actual question in the context =P

Why did you decide to use integer division instead of regular division? I'm not really sure how real/important the fractional parts are

**Comment by cclauss** [comment]
The current code wraps the calculation in __int()__ and this PR uses // because
__all(int(a / b) == a // b for a, b in ((1, 0.6), (1, 1.2), (10, 0.6), (100, 0.6), (0.6, 1)))__   # -> True

**Comment by StoicLoofah** [comment]
OH! I missed that `int()` in the original code. You definitely did that right. Also, I think using `1.0` as the default speed is probably more correct than `0.6`. So everything you initially did everything correct =P

If you revert that, I will approve and merge. Thanks (and apologies) for bearing with me!

**Comment by cclauss** [comment]
https://github.com/ggtracker/sc2reader/pull/102#pullrequestreview-311311684 So you want to default to __faster__, not __normal__?

**Comment by StoicLoofah** [comment]
Yes, let's default to faster. It will at least be ocrrect for alphastar and is the de facto default these for LotV ladder, right?

**Review by StoicLoofah — APPROVED** [review]

**Comment by StoicLoofah** [comment]
Thanks!

**Pull request merged**
