### PR TITLE
Add handler for command_update_target_unit_event

### PR DESCRIPTION
**Pull request by gravelweb**
This is one step towards fixing Zerg Macro (ggtracker/ggtrackerstack#13, ggtracker/ggtrackerstack#49) and Terran Macro (ggtracker/ggtrackerstack#48)

### CODE REVIEW

**Comment by dsjoerg** [comment]
Looks good.

Is this ready to roll into production?

What kind of testing has been done?

**Comment by dsjoerg** [comment]
The ideal would be
1) to verify that this commit doesn't affect currently passing tests (in the Testing section of README.md)
2) to add a test that breaks without this commit

**Comment by gravelweb** [comment]
@dsjoerg I was thinking about that after I powered down last night! I noticed the tests as I was greping through the code, but I totally forgot. What's the magic to run the test suite?

**Comment by dsjoerg** [comment]
@gravelweb It's here: https://github.com/ggtracker/sc2reader/blob/master/README.rst#testing

**Comment by gravelweb** [comment]
@dsjoerg Thanks. I'll try to get it done tonight. Sunday at the latest.

**Comment by dsjoerg** [comment]
OK @gravelweb and thanks to @nickelsen we now have CircleCI integration so that any commits will be tested automatically and the test status will be reported here for pull requests.

**Comment by gravelweb** [comment]
Neat! Exciting stuff, guys.

**Comment by gravelweb** [comment]
Created tests, and made implementation safer (per player ability tracker, and clear last ability when finding missing ability).

Still need to get changes into ggpyjobs to not pick up actions that didn't work, but for this project it should be all good.

**Comment by dsjoerg** [comment]
@gravelweb should this change go into production, or should it wait until ggpyjobs changes have been made?  I don't totally understand what impact this change alone would have on the macro stats users see.

**Comment by gravelweb** [comment]
@dsjoerg This will "fix" Terran and Protoss macro, since that plugin is not explicitly looking for TargetAbilityEvents. It will match on ability_name in the events, and it will find them UpdateTargetAbilityEvent. So for that, if we are not too worried about the extra events, it could go into production

Zerg macro is not affected since we _are_ explicitly looking for 'TargetAbilityEvent', so no change will occur yet here. So here we are indifferent to whether this patch is in production or not.

**Comment by dsjoerg** [comment]
OK @gravelweb would you like the honors of updating ggpyjobs to use the new sc2reader you've made?   And updating esdb to use the new ggpyjobs?  Then I will deploy everything into production and monitor for complaints/errors.

**Comment by gravelweb** [comment]
OK on it!

**Comment by gravelweb** [comment]
Doesn't sc2reader get picked up automagicly on startup? I can't seem to pinpoint where ggpyjobs looks for sc2reader version. It's not where I was expecting (requirements.txt)

**Comment by gravelweb** [comment]
Looking at git changelog, it looks like @nickelsen has got ggpyjobs tracking HEAD of upstream. Not sure how that will work for you when you deploy?

**Comment by dsjoerg** [comment]
@gravelweb you are correct.  so if i deploy it will automagically pick up the latest sc2reader. huzzah.  i will deploy, probably in ~12 hours.

**Comment by gravelweb** [comment]
Do you want to pickup my ggpyjobs changes too, so that ZergMacroTracker can start working too? :)

**Pull request merged**
