### PR TITLE
Reconcile graylinkim/master and ggtracker/upstream

### PR DESCRIPTION
**Pull request by StoicLoofah**
From a side discussion, we would like to make [ggtracker/sc2reader](https://github.com/ggtracker/sc2reader) the canonical, maintained repo for sc2reader because it is correctly patched for recent versions of the StarCraft 2 replay versions. However, it has fallen behind [GraylinKim/sc2reader](https://github.com/GraylinKim/sc2reader) while moving ahead in other directions, so this is my attempt to resolve all merge conflicts.

Originally, I ran into 3 issues when trying to use [ggtracker/sc2reader](https://github.com/ggtracker/sc2reader) instead of [StoicLoofah/sc2reader/lotv](https://github.com/StoicLoofah/sc2reader/tree/lotv) for [StoicLoofah/spawningtool](https://github.com/StoicLoofah/spawningtool)

1. It looks like PIL is a requirement for this build but was not as part of the original sc2reader. This is more than a requirements update normal issue because on my ubuntu 16.04 instance, I had to install the libjpeg package separately to get pillow to install properly.

2. "replay.gateway" was renamed to "replay.region", which is what I'm using https://github.com/GraylinKim/sc2reader/commit/0e6286fc868a6dabf7b33e8a8ff5d6e52891416b

3. i needed this fix https://github.com/GraylinKim/sc2reader/commit/c5d22d68ba802f36068ed7199cc157ee0521819b

Rather than just patch those issues, I went ahead and tried to merge all of [GraylinKim/sc2reader](https://github.com/GraylinKim/sc2reader), which appeared to work. All of the tests are passing after resolving the merge conflicts (in the merge itself) and making a few small patches to the tests.

Overall, it was pretty straightforward, with 2 notable refactors:

1. https://github.com/GraylinKim/sc2reader/commit/2b35c07e09eceafa47a0d1c9470bf3e5ffe18725 This was notable because on ggtracker, there was this code that was dependent on the old naming. I updated all of it to the graylin's naming https://github.com/ggtracker/sc2reader/commit/90bc21912507293ec1aeda9fcbb5dbb439aa6f03
2. no side effects on this one, but the renaming was worth noting https://github.com/GraylinKim/sc2reader/commit/dda41fbb378d137a67898140fa494a31df9de016

Unless you see a reason why this is a bad idea, I will plug this into production for Spawning Tool and see if anything crops up.

Also flagging @GraylinKim in case you have any thoughts on this.

One more thing: props to you guys on this library. I have only lightly dabbled with it, but I am always impressed by the scope when I have to poke into it like this. Great work.

### CODE REVIEW

**Comment by dsjoerg** [comment]
I'm terrified of accepting this PR because it may have changed things that GGTracker depends on.  I'll try it on https://github.com/dsjoerg/ggpyjobs now, but I expect the tests to fail and that it would be a lot of work to debug and deal with the issues.

I expect that a more targeted PR would be much less work to integrated into GGTracker.

Anyway I'll try it now with https://github.com/dsjoerg/ggpyjobs

**Comment by dsjoerg** [comment]
Yeah it dies instantly, the tests won't even run.

```
was:ggpyjobs david$ GGFACTORY_CACHE_DIR=testcache GGPYJOBS_CONFIG_PATH=config PYTHONPATH=src/sc2reader DJANGO_SECRETKEY=foo ./manage.py test sc2parse
/Users/david/Dropbox/Programming/ggpyjobs/src/sc2reader/sc2reader/engine/plugins/creeptracker.py:5: DeprecationWarning: the sets module is deprecated
  from sets import Set

ImportError: cannot import name GetFromHotkeyEvent

```

**Comment by StoicLoofah** [comment]
yeah, there were some big refactors that happened in there that we would have to tackle, but that seems like a necessary price to pay for re-unifying the 2 forks. Even if we weren't combining them, it's something that we would have to tackle if the main line was maintained anyways, right?

Will the refactor affect the ggtracker app more deeply than [ggpyjobs](https://github.com/dsjoerg/ggpyjobs)? I don't mind going through and cleaning up references in there if that's the obstacle. I thinkn Graylin did a good job of documenting the renaming in the CHANGELOG, so I can just work off of that to get the tests passing there.

On the plus side, I would note that although full crashes seem bad, I think they're pretty representative of the complexity here. If we fix those, then I don't think that we will have a lot of lingering issues

**Comment by dsjoerg** [comment]
i was imagining that instead of trying to port ggpyjobs to use the newer graylinkim sc2reader, it might be possible for spawningtool to be ported to use the older ggtracker-style sc2reader.  because i'm lazy and don't want to do any work regarding unification.

**Comment by dsjoerg** [comment]
And to answer your question, ggpyjobs is the only part of ggtracker that uses sc2reader.  If the ggpyjobs tests can pass then i'm pretty optimistic that the whole thing will work.

**Comment by StoicLoofah** [comment]
Got it. Would you mind if I took a shot at ggpyjobs to see if I could get that working against this branch?

**Comment by dsjoerg** [comment]
@StoicLoofah go for it!  It's open source, in fact all of ggtracker is, see https://github.com/ggtracker/ggtrackerstack

But really if the tests in https://github.com/dsjoerg/ggpyjobs pass then I'm optimistic that the rest will work.

**Comment by StoicLoofah** [comment]
Great! Thanks for your support and patience in getting this shipped. I'm also running it in production, and it appears to be working for me so far as well.

Let me know when you mark a release version and get it on pypi so I can update references in my project and socialize the change as well.

**Pull request merged**
