### PR TITLE
Test both Python and legacy Python on Circle CI 2.0

### PR DESCRIPTION
**Pull request by cclauss**
Move up to Circle CI v2.0 and test both Python 2 and Python 3 in parallel.  __Ready for review__.

Unit tests are blocked by the '__max_creep_spread__' issues described in #43

https://circleci.com/docs/2.0/workflows-waiting-status probably needs to be done.

### CODE REVIEW

**Comment by StoicLoofah** [comment]
changes look good to me!

**Comment by cclauss** [comment]
@dsjoerg Your review please?

**Comment by dsjoerg** [comment]
Hey @StoicLoofah if you are cool with this you can merge in this PR and accept it.

@cclauss I'm no longer actively maintaining this repo.  I'll try to be helpful and answer questions when I can.

**Comment by StoicLoofah** [comment]
Thanks! Let me know if you figure out a fix for that creep spread issue.

**Pull request merged**
